name: Auto Academic Scraper

on:
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Dependencies
      run: pip install requests beautifulsoup4 google-genai pydantic

    # 明确告诉它在当前目录下运行
    - name: Run Scraper
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python ./scraper.py
