name: Auto Academic Scraper

on:
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 【关键修改】添加这行命令，让 GitHub 在运行前把目录下的文件全部列出来
    - name: Debug - List files
      run: ls -R

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Dependencies
      run: pip install requests beautifulsoup4 google-genai pydantic

    - name: Run Scraper Script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python scraper.py
